### ISSUE TITLE
Add try_into for getting a char out of a CharacterResult

### ISSUE THREAD

**Issue by alexanderkjall** [narfit66/ncursesw-rs#1]
Hi

Maybe I'm missing something obvious, but I have been trying to figure out how to obtain a char / i32 from the getch() function call without success.

Would it maybe be useful to implement try_into into char for that?

**Comment by narfit66** [comment]
Hi there @alexanderkjall 

The `getch()` family of functions return a result type of `CharacterResult<char>`, this is due to the fact that if the `keypad()` function has been called with a flag of `true` the NCurses library will interpret some keys such as function keys, home, end etc. This means that it has to return in a meaningful manner and this is done by using an enum with either a `CharacterResult::Key(KeyBinding)` for the interpreted keys (this may also include such things as mouse and resizing events) or a `CharacterResult::Character(char)` for non-interpreted keys. So… in short the `CharacterResult::Character()` enum will wrap the `char` value that you are looking for.

If you wanted to access the raw `i32` returned from NCurses you could always call `ncursesw::shims::ncurses::getch()` but you then of course loose the higher level interpretation of what the `i32` represents including if an error has occurred.

The `get_wch()` family of functions does exactly the same but returns a result type of `CharacterResult<WideChar>` instead of a `CharacterResult<char>`.

I’ve add `examples/getch-test.rs` to show how the result of a call to `getch()` can be interpreted, I hope this helps. I will also update the documentation for the next cargo release.

Best regards
Steve
